#	$OpenBSD: Makefile,v 1.53 2021/05/01 16:11:10 visa Exp $
#	$NetBSD: Makefile,v 1.5 1995/09/15 21:05:21 pk Exp $

SUBDIR=	dev/microcode \
	arch/amd64

tags:
	cd kern; make tags

include cobalt.subdir.mk
