PROG=	bioctl
BINDIR=${SBINDIR}

LIBS=	-lutil

CFLAGS=     -Wall
CFLAGS+=    -Wpointer-arith
CFLAGS+=    -Wno-uninitialized
CFLAGS+=    -Wstrict-prototypes
CFLAGS+=    -Wmissing-prototypes
CFLAGS+=    -Wunused
CFLAGS+=    -Wsign-compare
CFLAGS+=    -Wshadow

MAN=	bioctl.8

include cobalt.prog.mk
