#m4 make \
#stty test banner2 factor fortune grdc morse number primes tetris worm locale mklocale ksh ofetch login-ng unicode shsecret freq arch banner basename cat cmp comm cp cut date dd diff dirname doas echo expr false fold getopt indent hostname jot kill ln logger ls logname mkdir mktemp mv nl printenv printf pwd readlink realpath rev rm rmdir rs seq sleep split timeout touch tr true tsort tty uname unifdef uniq units unvis vis wc yes sponge hexedit
#sndioctl sndiod nbperf tic tput

SUBDIR= apply at audioctl awk \
	cal cap_mkdb cdio chpass \
	crontab ctfconv ctfdump \
	cu \
	du encrypt env \
	find finger fmt fstat gencat getcap \
	getconf getent gprof grep head hexdump id \
	ipcrm ipcs \
	join kdump kstat ktrace \
	last \
	locate lock login look lorder \
	make \
	mixerctl netstat \
	newsyslog \
	nice nm nohup pagesize passwd patch pctr \
	pkill \
	renice rpcgen rpcinfo \
	sdiff script sed shar signify \
	sort spell spellprog stat su \
	tail tcpbench tee time timeout \
	ts usbhidaction usbhidctl \
	users uudecode uuencode vmstat w \
	what which who whois xargs xinstall \
	chmod df ps sync \
	stty test banner2 factor fortune morse number primes tetris locale mklocale ofetch login-ng unicode shsecret freq arch banner basename cat cmp comm cp cut date dd diff dirname doas echo expr false fold getopt indent hostname jot kill ln logger ls logname mkdir mktemp mv nl printenv printf pwd readlink realpath rev rm rmdir rs seq sleep split timeout touch tr true tsort tty uname unifdef uniq units unvis vis wc yes sponge

include cobalt.subdir.mk
#TODO
