#pragma once

#define HAVE_DECL_MEMRCHR
#define HAVE_DECL_MEMMEM
#define HAVE_DECL_MEMRMEM
#define HAVE_DECL_BASENAME
#define HAVE_STRERROR
#define HAVE_STRDUP

#define HAVE_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_LIBGEN_H 1
#define HAVE_SYS_MOUNT_H 1
