#	$OpenBSD: Makefile,v 1.5 2016/02/01 22:38:01 gsoares Exp $

MAN=	hexedit.1

PROG=	hexedit
SRCS=	hexedit.c file.c mark.c misc.c page.c display.c interact.c search.c

LDADD=	-lcurses

.include <bsd.prog.mk>
