	#config cron crunchgen dev_mkdb \
	#hotplugd ifstated installboot iostat \
	#mkuboot mtree netgroup_mkdb \
	#badsect bioctl dhclient dhcpleased disklabel dmesg dump dumpfs fdisk fsck fsck_ext2fs fsck_ffs fsck_msdos fsdb fsirand growfs ifconfig init kbd ldattach mknod mount mount_cd9660 mount_ext2fs mount_ffs mount_msdos mount_ntfs mount_tmpfs mount_vnd ncheck_ffs newfs newfs_ext2fs newfs_msdos nologin pfctl pflogd ping reboot resolvd restore savecore scan_ffs scsi shutdown sysctl ttyflags tunefs umount vnconfig wsconsctl chroot

SUBDIR=	ac accton acpidump rmgroup apm apmd arp authpf \
	cron dev_mkdb \
	dhcpleasectl \
	cron crunchgen dev_mkdb \
	hostctl \
	kgmon kvm_mkdb \
	hotplugd installboot iostat \
	makefs memconfig \
	mtree netgroup_mkdb \
	pcidump procmap pstat pwd_mkdb \
	rcctl rdsetroot \
	sensorsd \
	syslogc syslogd \
	tcpdrop traceroute \
	usbdevs user vmd vmctl vipw \
	watchdogd wsconscfg wsfontload wsmoused \
	badsect bioctl dhclient dmesg dump dumpfs fsck fsirand growfs ifconfig init ldattach mknod mount ncheck_ffs newfs_msdos nologin ping reboot resolvd savecore scan_ffs scsi shutdown ttyflags tunefs umount vnconfig chroot

include cobalt.subdir.mk
#TODO
