#	$OpenBSD: Makefile,v 1.9 2013/04/15 06:25:18 deraadt Exp $

PROG=	mtree
#CFLAGS+=-DDEBUG
MAN=	mtree.8
OBJS=	compare.o crc.o create.o misc.o mtree.o spec.o verify.o
BINDIR=${SBINDIR}

include cobalt.prog.mk
