#!/usr/bin/env zsh

# Adapted from Linux From Scratch's copy-trust-modifications

ANCHORDIR='/etc/pki/anchors'
ANCHORLIST='/etc/pki/anchors.md5sums'
LOCALDIR='/etc/ssl/local'
MD5SUM='/usr/bin/md5sum'

# Dump to a temporary directory
TEMPDIR=`mktemp -d`
/usr/bin/trust extract --filter=certificates --format=openssl-directory --overwrite "${TEMPDIR}"

# Create a list of anchors that were not present or have been modified
for SUM in $(ls -1 "${ANCHORDIR}"); do
	cat "${ANCHORDIR}/${SUM}" | "${MD5SUM}" 2> /dev/null >> "${TEMPDIR}/anchors/md5sums"
done
diff -au "${ANCHORLIST}" "${TEMPDIR}/anchors.md5sums" 2> /dev/null > "${TEMPDIR}/diff" 
grep "^+[a-z,0-9]" "${TEMPDIR}/diff" | cut -d " " -f 3 | sed '/x-certificate-extension/d' 2> /dev/null > "${TEMPDIR}/certlist"

echo -e "\nThe following certificates have local modifications:\n"

# Copy new certificates to LOCALDIR
for CERT in `cat "${TEMPDIR}/certlist"` ; do
	LABEL=`grep -m 1 "^label:" "${CERT}" | sed 's@^label: @@'`
	LABELNEW=`echo "${LABEL}" | sed -e 's@"@@g' -e 's@ @_@g'`

	# Determine default usage (this can be changed later)
	usage=$(openssl x509 -in ${CERT} -noout -text | grep -A1 "X509v3 Key Usage:")
	trust=""
	echo ${usage} | grep -q "Certificate Sign" && trust="${trust} -addtrust serverAuth"
	echo ${usage} | grep -q "Digital Signature" && trust="${trust} -addtrust emailProtection"

	# Place into LOCALDIR
	openssl x509 -in ${CERT} -text -fingerprint -setalias "${LABEL}" ${trust} -out "${LOCALDIR}/${LABELNEW}.pem"
	echo -e "${LABELNEW}"
	unset LABEL LABELNEW usage trust
done
echo ""

# Clean up
rm -rf "${TEMPDIR}"
unset ANCHORDIR ANCHORLIST LOCALDIR CERTLIST TEMPDIR
