PROG=	crontab
OBJS=	crontab.o entry.o env.o client.o misc.o
CFLAGS+=-I${CURDIR}/../../usr.sbin/cron
BINGRP =crontab
BINMODE=2555
MAN=	crontab.1 crontab.5

#.PATH: ${.CURDIR}/../../usr.sbin/cron

include cobalt.prog.mk
