#	$OpenBSD: Makefile,v 1.82 2021/12/01 07:36:03 patrick Exp $
#	$NetBSD: Makefile,v 1.20.4.1 1996/06/14 17:22:38 cgd Exp $

SUBDIR=	libarch libz \
	libedit libevent \
	libpcap \
	libusbhid \
	liby

#TODO: csu libc libkvm libm librthread libutil libelf libfuse libiberty

.include <bsd.subdir.mk>
