CFLAGS=-I../lib/util -I../lib
LDFLAGS=-L../lib -lpbm -lm

all: pamcrater pamgauss pamgradient pamseq pamshadedrelief pamstereogram pbmmake pbmpage pbmtext pbmtextps pgmkernel pgmmake pgmnoise pgmramp ppmcie ppmforge ppmmake ppmpat ppmrough ppmwheel

clean:
	rm -fv pamcrater pamgauss pamgradient pamseq pamshadedrelief pamstereogram pbmmake pbmpage pbmtext pbmtextps pgmkernel pgmmake pgmnoise pgmramp ppmcie ppmforge ppmmake ppmpat ppmrough ppmwheel
