.Dd $Mdocdate: January 12 2024 $
.Dt LOGIN-NG 1
.Os
.Sh NAME
.Nm login-ng
.Nd log into the computer (visually improved)
.Sh SYNOPSIS
.Nm login-ng
.Sh DESCRIPTION
The
.Nm
utility provides an interactive terminal interface for logging into the system, or for switching user accounts.
.El
.Sh SEE ALSO
.Xr login 1 ,
.Xr chpass 1 ,
.Xr passwd 1 ,
.Xr su 1 ,
.Xr readpassphrase 3 ,
.Xr setusercontext 3 ,
.Xr fbtab 5 ,
.Xr login.conf 5 ,
.Xr utmp 5 ,
.Xr environ 7
.Sh HISTORY
A
.Nm
utility appeared in Cobalt 1.0.
