#	from: @(#)Makefile	5.7 (Berkeley) 4/1/91
#	$OpenBSD: Makefile,v 1.68 2022/09/01 14:22:56 martijn Exp $

.include <bsd.own.mk>

#TODO: ld.so

SUBDIR= getty login_chpass \
	login_lchpass login_passwd login_reject \
	reorder_kernel \
	security

.include <bsd.subdir.mk>
