CFLAGS=-I../lib/util -I../lib
LDFLAGS=-L../lib -lpbm -lm

all: pamarith pambayer pamchannel pamdepth pamendian pamexec pamfix pamlookup pampick pamsplit pamstack pamsummcol pamunlookup pamvalidate pnmcolormap ppmdcfont ppmddumpfont ppmdmkfont

clean:
	rm -fv pamarith pambayer pamchannel pamdepth pamendian pamexec pamfix pamlookup pampick pamsplit pamstack pamsummcol pamunlookup pamvalidate pnmcolormap ppmdcfont ppmddumpfont ppmdmkfont
