PROG=make

OBJS= \
      main.o \
      misc.o \
      output.o \
      read.o \
      job.o \
      rule.o \
      variable.o \
      file.o \
      remake.o \
      load.o \
      vpath.o \
      posixos.o \
      shuffle.o \
      version.o \
      expand.o \
      function.o \
      dir.o \
      strcache.o \
      commands.o \
      hash.o \
      implicit.o \
      default.o \
      ar.o \
      arscan.o \
      loadapi.o \
      remote-stub.o

CFLAGS=-I. -Wno-string-compare -DLIBDIR=\".\"

include cobalt.prog.mk
