all:

clean:

install:
	mkdir -p "${DESTDIR}/usr/X11R6/lib/X11/fonts/base-fonts
	cp -rfv \
		Anek_Devanagari \
		AwamiNastaliq-3.000 \
		DaiBannaSIL-4.000 \
		Harmattan-2.000 \
		NotoSansCJK-JP \
		Noto_Color_Emoji \
		Noto_Sans \
		Noto_Sans_Bengali \
		Noto_Sans_Buginese \
		Noto_Sans_Cherokee \
		Noto_Sans_Glagolitic \
		Noto_Sans_Gothic \
		Noto_Sans_Gurmukhi \
		Noto_Sans_Kannada \
		Noto_Sans_Khmer \
		Noto_Sans_Malayalam \
		Noto_Sans_Meetei_Mayek \
		Noto_Sans_Miao \
		Noto_Sans_Mongolian \
		Noto_Sans_Ol_Chiki \
		Noto_Sans_Oriya \
		Noto_Sans_Sinhala \
		Noto_Sans_Syriac \
		Noto_Sans_Telugu \
		Noto_Sans_Thaana \
		Noto_Serif_Thai \
		Noto_Serif_Tibetan \
		Padauk-5.001 \
		SophiaNubian \
		TaiHeritagePro-2.600 \
		TuladhaJejegGr_2.01 \
		aakar-medium.ttf \
		dejavu-fonts-ttf-2.37 \
		nlci-taml-auvaiyar-0.800 \
		zotosans-ethiopic.ttf \
		"${DESTDIR}/usr/X11R6/lib/X11/fonts/base-fonts"
