CFLAGS=-I../lib/util -I../lib
LDFLAGS=-L../lib -lpbm -lm

all: pamfile pammosaicknit pamsharpmap pamsharpness pamslice pamsumm pamtilt pbmminkowski pgmhist pgmminkowski pgmtexture pnmhistmap pnmpsnr ppmhist

clean:
	rm -fv pamfile pammosaicknit pamsharpmap pamsharpness pamslice pamsumm pamtilt pbmminkowski pgmhist pgmminkowski pgmtexture pnmhistmap pnmpsnr ppmhist
