SUBDIR=	libstubs \
	arch bioctl cat chmod chroot cp date dd df dhcpleased disklabel \
	dmesg doas eeprom encrypt fsck fsck_ext2fs fsck_ffs fsck_msdos ftp \
	ftp-ssl grep growfs gzip hostname ifconfig init installboot kbd ksh ln \
	ls mkdir mknod mkuboot more mount mount_cd9660 mount_ext2fs \
	mount_ffs mount_msdos mount_nfs mount_udf mt mv newfs newfs_ext2fs \
	newfs_msdos pdisk ping pwd_mkdb reboot resolvd restore rm route sed \
	signify slaacd sleep stty sync sysctl tee umount

install:

include bsd.subdir.mk


