.Dd $Mdocdate: September 12 2023 $
.Dt WISDOM 6
.Os
.Sh NAME
.Nm wisdom
.Nd print unique wisdom every day
.Sh SYNOPSIS
.Nm wisdom
.Oc
.Sh DESCRIPTION
.Nm
prints out a unique randomly-generated phrase depending on the day.
Unlike fortune(6), every day has a single unique phrase assigned to
it, and the phrases are generated at random.
.Sh HISTORY
.Nm
first appeared in Cobalt 1.0. It was released in 1999 by David Madore
as Wisdom of the Day.
