PROG=	locate
OBJS=	util.o locate.o
MAN=	locate.1


# only /usr/src/etc/Makefile install files in /etc
#	${INSTALL} ${INSTALL_COPY} -o root -g wheel -m 644 \
#		${.CURDIR}/locate.rc ${DESTDIR}/etc

include cobalt.prog.mk
