all:
	echo "Run make install to compile and install"

#TODO
install:
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge LuaJIT
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge byacc
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge bzip2
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge cairo
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge compton
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge curl
	#GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge dialog
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge expat
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge ffmpeg
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge file
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge flex
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge fribidi
	#GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge htop
	#GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge idesk
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge imlib2
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge jpeg
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge jwm
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge less
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge libarchive
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge libass
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge libpng
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge libressl
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge libtasn1
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge mandoc
	#GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge mpv
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge muon
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge nasm
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge ncurses
	#GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge neosurf
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge nickle
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge nsxiv
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge p11-kit
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge pax-utils
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge pigz
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge pkgconf
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge rhash
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge samurai
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge selx
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge sndio
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge st
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge sxot
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge tinycc
	#GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge tmux
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge tzdb
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge vim
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge xlockmore
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge xz
	#GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge zsh
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge zsh-autosuggestions
	GUEST=${DESTDIR} REPODIR=${CURDIR} SRCDIR=${CURDIR}/dist pkg merge zsh-syntax-highlighting

clean:
	echo "Nothing to do."
