PROG=	ifstated
OBJS=	ifstated.o log.o parse.o
CFLAGS+= -Wall
CFLAGS+= -Wstrict-prototypes -Wmissing-prototypes
CFLAGS+= -Wmissing-declarations
CFLAGS+= -Wshadow -Wpointer-arith -Wcast-qual
MAN= ifstated.8 ifstated.conf.5
LIBS=-levent

include cobalt.prog.mk
#TODO
